(("begin" NIL)
 ((("if" NIL)
   ((((NIL
       (("(" NIL)
        ((((NIL ((NIL #\a NIL NIL) NIL)) NIL) NIL)
         ((">" NIL) ((((NIL ((NIL #\b NIL NIL) NIL)) NIL) NIL) NIL)))
        (")" NIL)))
      NIL)
     NIL)
    NIL)
   ("then" NIL)
   (("begin" NIL)
    ((((NIL #\a NIL NIL) NIL) (":=" NIL)
      ((((NIL ((NIL #\b NIL NIL) NIL)) NIL) NIL) NIL))
     NIL)
    ("end" NIL))
   NIL)
  NIL)
 ("end" NIL))