(PROGN
 (ESRAP:DEFRULE SWTOOLSPROGRAM
     (AND (+ (AND FILE_CUT (* COMMENT) BLOCK)) ENDOFFILE))
 (ESRAP:DEFRULE IDENTIFIER
     IDENT)
 (ESRAP:DEFRULE BLOCK
     (AND
      (*
       (OR LABELDECLARATIONPART CONSTANTDEFINITIONPART TYPEDEFINITIONPART
           VARIABLEDECLARATIONPART PROCEDUREANDFUNCTIONDECLARATIONPART
           USESUNITSPART IMPLEMENTATION))
      COMPOUNDSTATEMENT))
 (ESRAP:DEFRULE USESUNITSPART
     (AND USES IDENTIFIERLIST SEMI))
 (ESRAP:DEFRULE LABELDECLARATIONPART
     (AND LABEL LABEL (* (AND COMMA LABEL)) SEMI))
 (ESRAP:DEFRULE LABEL
     UNSIGNEDINTEGER)
 (ESRAP:DEFRULE CONSTANTDEFINITIONPART
     (AND CONST (+ (AND CONSTANTDEFINITION SEMI))))
 (ESRAP:DEFRULE CONSTANTDEFINITION
     (AND IDENTIFIER EQUAL CONSTANT))
 (ESRAP:DEFRULE CONSTANTCHR
     (AND CHR LPAREN UNSIGNEDINTEGER RPAREN))
 (ESRAP:DEFRULE CONSTANT
     (OR UNSIGNEDNUMBER (AND SIGN UNSIGNEDNUMBER) IDENTIFIER
         (AND SIGN IDENTIFIER) STRING CONSTANTCHR))
 (ESRAP:DEFRULE UNSIGNEDNUMBER
     (OR UNSIGNEDINTEGER UNSIGNEDREAL))
 (ESRAP:DEFRULE UNSIGNEDINTEGER
     NUM_INT)
 (ESRAP:DEFRULE UNSIGNEDREAL
     NUM_REAL)
 (ESRAP:DEFRULE SIGN
     (OR PLUS MINUS))
 (ESRAP:DEFRULE BOOL
     (OR TRUE FALSE))
 (ESRAP:DEFRULE STRING
     STRING_LITERAL)
 (ESRAP:DEFRULE TYPEDEFINITIONPART
     (AND TYPE (+ (AND TYPEDEFINITION SEMI))))
 (ESRAP:DEFRULE TYPEDEFINITION
     (AND IDENTIFIER EQUAL (OR TYPE FUNCTIONTYPE PROCEDURETYPE)))
 (ESRAP:DEFRULE FUNCTIONTYPE
     (AND FUNCTION (ESRAP:? FORMALPARAMETERLIST) COLON RESULTTYPE))
 (ESRAP:DEFRULE PROCEDURETYPE
     (AND PROCEDURE (ESRAP:? FORMALPARAMETERLIST)))
 (ESRAP:DEFRULE TYPE
     (OR SIMPLETYPE STRUCTUREDTYPE POINTERTYPE))
 (ESRAP:DEFRULE SIMPLETYPE
     (OR SCALARTYPE SUBRANGETYPE TYPEIDENTIFIER STRINGTYPE))
 (ESRAP:DEFRULE SCALARTYPE
     (AND LPAREN IDENTIFIERLIST RPAREN))
 (ESRAP:DEFRULE SUBRANGETYPE
     (AND CONSTANT DOTDOT CONSTANT))
 (ESRAP:DEFRULE TYPEIDENTIFIER
     (OR IDENTIFIER (OR CHAR BOOLEAN INTEGER REAL STRING)))
 (ESRAP:DEFRULE STRUCTUREDTYPE
     (OR (AND PACKED UNPACKEDSTRUCTUREDTYPE) UNPACKEDSTRUCTUREDTYPE))
 (ESRAP:DEFRULE UNPACKEDSTRUCTUREDTYPE
     (OR ARRAYTYPE RECORDTYPE SETTYPE FILETYPE))
 (ESRAP:DEFRULE STRINGTYPE
     (AND STRING LBRACK (OR IDENTIFIER UNSIGNEDNUMBER) RBRACK))
 (ESRAP:DEFRULE ARRAYTYPE
     (OR (AND ARRAY LBRACK TYPELIST RBRACK OF COMPONENTTYPE)
         (AND ARRAY LBRACK2 TYPELIST RBRACK2 OF COMPONENTTYPE)))
 (ESRAP:DEFRULE TYPELIST
     (AND INDEXTYPE (* (AND COMMA INDEXTYPE))))
 (ESRAP:DEFRULE INDEXTYPE
     SIMPLETYPE)
 (ESRAP:DEFRULE COMPONENTTYPE
     TYPE)
 (ESRAP:DEFRULE RECORDTYPE
     (AND RECORD (ESRAP:? FIELDLIST) END))
 (ESRAP:DEFRULE FIELDLIST
     (OR (AND FIXEDPART (ESRAP:? (AND SEMI VARIANTPART))) VARIANTPART))
 (ESRAP:DEFRULE FIXEDPART
     (AND RECORDSECTION (* (AND SEMI RECORDSECTION))))
 (ESRAP:DEFRULE RECORDSECTION
     (AND IDENTIFIERLIST COLON TYPE))
 (ESRAP:DEFRULE VARIANTPART
     (AND CASE TAG OF VARIANT (* (AND SEMI VARIANT))))
 (ESRAP:DEFRULE TAG
     (OR (AND IDENTIFIER COLON TYPEIDENTIFIER) TYPEIDENTIFIER))
 (ESRAP:DEFRULE VARIANT
     (AND CONSTLIST COLON LPAREN FIELDLIST RPAREN))
 (ESRAP:DEFRULE SETTYPE
     (AND SET OF BASETYPE))
 (ESRAP:DEFRULE BASETYPE
     SIMPLETYPE)
 (ESRAP:DEFRULE FILETYPE
     (OR (AND FILE OF TYPE) FILE))
 (ESRAP:DEFRULE POINTERTYPE
     (AND POINTER TYPEIDENTIFIER))
 (ESRAP:DEFRULE VARIABLEDECLARATIONPART
     (AND VAR VARIABLEDECLARATION (* (AND SEMI VARIABLEDECLARATION)) SEMI))
 (ESRAP:DEFRULE VARIABLEDECLARATION
     (AND IDENTIFIERLIST COLON TYPE))
 (ESRAP:DEFRULE PROCEDUREANDFUNCTIONDECLARATIONPART
     (AND PROCEDUREORFUNCTIONDECLARATION SEMI))
 (ESRAP:DEFRULE PROCEDUREORFUNCTIONDECLARATION
     (OR PROCEDUREDECLARATION FUNCTIONDECLARATION))
 (ESRAP:DEFRULE PROCEDUREDECLARATION
     (AND PROCEDURE IDENTIFIER SPACING (ESRAP:? FORMALPARAMETERLIST) SEMI
          BLOCK))
 (ESRAP:DEFRULE FORMALPARAMETERLIST
     (AND LPAREN FORMALPARAMETERSECTION (* (AND SEMI FORMALPARAMETERSECTION))
          RPAREN))
 (ESRAP:DEFRULE FORMALPARAMETERSECTION
     (OR PARAMETERGROUP (AND VAR PARAMETERGROUP) (AND FUNCTION PARAMETERGROUP)
         (AND PROCEDURE PARAMETERGROUP)))
 (ESRAP:DEFRULE PARAMETERGROUP
     (AND IDENTIFIERLIST SPACING COLON TYPEIDENTIFIER))
 (ESRAP:DEFRULE IDENTIFIERLIST
     (AND IDENTIFIER (* (AND COMMA IDENTIFIER))))
 (ESRAP:DEFRULE CONSTLIST
     (AND CONSTANT (* (AND COMMA CONSTANT))))
 (ESRAP:DEFRULE FUNCTIONDECLARATION
     (AND FUNCTION IDENTIFIER (ESRAP:? FORMALPARAMETERLIST) COLON RESULTTYPE
          SEMI BLOCK))
 (ESRAP:DEFRULE RESULTTYPE
     TYPEIDENTIFIER)
 (ESRAP:DEFRULE STATEMENT
     (OR (AND LABEL COLON UNLABELLEDSTATEMENT) UNLABELLEDSTATEMENT))
 (ESRAP:DEFRULE UNLABELLEDSTATEMENT
     (OR STRUCTUREDSTATEMENT SIMPLESTATEMENT))
 (ESRAP:DEFRULE SIMPLESTATEMENT
     (OR ASSIGNMENTSTATEMENT PROCEDURESTATEMENT GOTOSTATEMENT))
 (ESRAP:DEFRULE ASSIGNMENTSTATEMENT
     (AND VARIABLE ASSIGN EXPRESSION))
 (ESRAP:DEFRULE VARIABLE
     (AND (OR (AND AT IDENTIFIER) IDENTIFIER)
          (*
           (OR (AND LBRACK EXPRESSION (* (AND COMMA EXPRESSION)) RBRACK)
               (AND LBRACK2 EXPRESSION (* (AND COMMA EXPRESSION)) RBRACK2)
               (AND DOT IDENTIFIER) POINTER))))
 (ESRAP:DEFRULE EXPRESSION
     (AND SIMPLEEXPRESSION (ESRAP:? (AND RELATIONALOPERATOR EXPRESSION))))
 (ESRAP:DEFRULE RELATIONALOPERATOR
     (OR EQUAL NOT_EQUAL LT LE GE GT IN))
 (ESRAP:DEFRULE SIMPLEEXPRESSION
     (AND TERM (ESRAP:? (AND ADDITIVEOPERATOR SIMPLEEXPRESSION))))
 (ESRAP:DEFRULE ADDITIVEOPERATOR
     (OR PLUS MINUS OR))
 (ESRAP:DEFRULE TERM
     (AND SIGNEDFACTOR (ESRAP:? (AND MULTIPLICATIVEOPERATOR TERM))))
 (ESRAP:DEFRULE MULTIPLICATIVEOPERATOR
     (OR STAR SLASH DIV MOD AND))
 (ESRAP:DEFRULE SIGNEDFACTOR
     (AND (ESRAP:? (OR PLUS MINUS)) FACTOR))
 (ESRAP:DEFRULE FACTOR
     (OR VARIABLE (AND LPAREN EXPRESSION RPAREN) FUNCTIONDESIGNATOR
         UNSIGNEDCONSTANT SET (AND NOT FACTOR) BOOL))
 (ESRAP:DEFRULE UNSIGNEDCONSTANT
     (OR UNSIGNEDNUMBER CONSTANTCHR STRING CNIL))
 (ESRAP:DEFRULE FUNCTIONDESIGNATOR
     (AND IDENTIFIER LPAREN PARAMETERLIST RPAREN))
 (ESRAP:DEFRULE PARAMETERLIST
     (AND ACTUALPARAMETER (* (AND COMMA ACTUALPARAMETER))))
 (ESRAP:DEFRULE SET
     (OR (AND LBRACK ELEMENTLIST RBRACK) (AND LBRACK2 ELEMENTLIST RBRACK2)))
 (ESRAP:DEFRULE ELEMENTLIST
     (ESRAP:? ELEMENTLST))
 (ESRAP:DEFRULE ELEMENTLST
     (AND ELEMENT (* (AND COMMA ELEMENT))))
 (ESRAP:DEFRULE ELEMENT
     (AND EXPRESSION (ESRAP:? (AND DOTDOT EXPRESSION))))
 (ESRAP:DEFRULE PROCEDURESTATEMENT
     (AND IDENTIFIER (ESRAP:? (AND LPAREN PARAMETERLIST RPAREN))))
 (ESRAP:DEFRULE ACTUALPARAMETER
     (AND EXPRESSION (* PARAMETERWIDTH)))
 (ESRAP:DEFRULE PARAMETERWIDTH
     (AND ":" EXPRESSION))
 (ESRAP:DEFRULE GOTOSTATEMENT
     (AND GOTO LABEL))
 (ESRAP:DEFRULE STRUCTUREDSTATEMENT
     (OR COMPOUNDSTATEMENT CONDITIONALSTATEMENT REPETETIVESTATEMENT
         WITHSTATEMENT))
 (ESRAP:DEFRULE COMPOUNDSTATEMENT
     (AND BEGIN STATEMENTS END))
 (ESRAP:DEFRULE STATEMENTS
     (AND STATEMENT (* (AND SEMI STATEMENT))))
 (ESRAP:DEFRULE CONDITIONALSTATEMENT
     (OR IFSTATEMENT CASESTATEMENT))
 (ESRAP:DEFRULE IFSTATEMENT
     (AND IF EXPRESSION THEN STATEMENT (ESRAP:? (AND ELSE STATEMENT))))
 (ESRAP:DEFRULE CASESTATEMENT
     (AND CASE EXPRESSION OF CASELISTELEMENT (* (AND SEMI CASELISTELEMENT))
          (ESRAP:? (AND SEMI ELSE STATEMENTS)) END))
 (ESRAP:DEFRULE CASELISTELEMENT
     (AND CONSTLIST COLON STATEMENT))
 (ESRAP:DEFRULE REPETETIVESTATEMENT
     (OR WHILESTATEMENT REPEATSTATEMENT FORSTATEMENT))
 (ESRAP:DEFRULE WHILESTATEMENT
     (AND WHILE EXPRESSION DO STATEMENT))
 (ESRAP:DEFRULE REPEATSTATEMENT
     (AND REPEAT STATEMENTS UNTIL EXPRESSION))
 (ESRAP:DEFRULE FORSTATEMENT
     (AND FOR IDENTIFIER ASSIGN FORLIST DO STATEMENT))
 (ESRAP:DEFRULE FORLIST
     (AND INITIALVALUE (OR TO DOWNTO) FINALVALUE))
 (ESRAP:DEFRULE INITIALVALUE
     EXPRESSION)
 (ESRAP:DEFRULE FINALVALUE
     EXPRESSION)
 (ESRAP:DEFRULE WITHSTATEMENT
     (AND WITH RECORDVARIABLELIST DO STATEMENT))
 (ESRAP:DEFRULE RECORDVARIABLELIST
     (AND VARIABLE (* (AND COMMA VARIABLE))))
 (ESRAP:DEFRULE AND
     "and")
 (ESRAP:DEFRULE ARRAY
     (AND "array" SPACING))
 (ESRAP:DEFRULE BEGIN
     (AND "begin" SPACING))
 (ESRAP:DEFRULE BOOLEAN
     (AND "boolean" SPACING))
 (ESRAP:DEFRULE CASE
     (AND "case" SPACING))
 (ESRAP:DEFRULE CHAR
     (AND "char" SPACING))
 (ESRAP:DEFRULE CHR
     (AND "chr" SPACING))
 (ESRAP:DEFRULE CONST
     (AND "const" SPACING))
 (ESRAP:DEFRULE DIV
     (AND "div" SPACING))
 (ESRAP:DEFRULE DO
     (AND "do" SPACING))
 (ESRAP:DEFRULE DOWNTO
     (AND "downto" SPACING))
 (ESRAP:DEFRULE ELSE
     (AND "else" SPACING))
 (ESRAP:DEFRULE END
     (AND "end" SPACING))
 (ESRAP:DEFRULE FILE
     (AND "file" SPACING))
 (ESRAP:DEFRULE FOR
     (AND "for" SPACING))
 (ESRAP:DEFRULE FUNCTION
     (AND "function" SPACING))
 (ESRAP:DEFRULE GOTO
     (AND "goto" SPACING))
 (ESRAP:DEFRULE IF
     (AND "if" SPACING))
 (ESRAP:DEFRULE IN
     (AND "in" SPACING))
 (ESRAP:DEFRULE INTEGER
     (AND "integer" SPACING))
 (ESRAP:DEFRULE LABEL
     (AND "label" SPACING))
 (ESRAP:DEFRULE MOD
     (AND "mod" SPACING))
 (ESRAP:DEFRULE CNIL
     (AND "nil" SPACING))
 (ESRAP:DEFRULE NOT
     (AND "not" SPACING))
 (ESRAP:DEFRULE OF
     (AND "of" SPACING))
 (ESRAP:DEFRULE OR
     (AND "or" SPACING))
 (ESRAP:DEFRULE PACKED
     (AND "packed" SPACING))
 (ESRAP:DEFRULE PROCEDURE
     (AND "procedure" SPACING))
 (ESRAP:DEFRULE PROGRAM
     (AND "program" SPACING))
 (ESRAP:DEFRULE REAL
     (AND "real" SPACING))
 (ESRAP:DEFRULE RECORD
     (AND "record" SPACING))
 (ESRAP:DEFRULE REPEAT
     (AND "repeat" SPACING))
 (ESRAP:DEFRULE SET
     (AND "set" SPACING))
 (ESRAP:DEFRULE THEN
     (AND "then" SPACING))
 (ESRAP:DEFRULE TO
     (AND "to" SPACING))
 (ESRAP:DEFRULE TYPE
     (AND "type" SPACING))
 (ESRAP:DEFRULE UNTIL
     (AND "until" SPACING))
 (ESRAP:DEFRULE VAR
     (AND "var" SPACING))
 (ESRAP:DEFRULE WHILE
     (AND "while" SPACING))
 (ESRAP:DEFRULE WITH
     (AND "with" SPACING))
 (ESRAP:DEFRULE PLUS
     (AND "+" SPACING))
 (ESRAP:DEFRULE MINUS
     (AND "-" SPACING))
 (ESRAP:DEFRULE STAR
     (AND "*" SPACING))
 (ESRAP:DEFRULE SLASH
     (AND "/" SPACING))
 (ESRAP:DEFRULE ASSIGN
     (AND ":=" SPACING))
 (ESRAP:DEFRULE COMMA
     (AND "," SPACING))
 (ESRAP:DEFRULE SEMI
     (AND ";" SPACING))
 (ESRAP:DEFRULE COLON
     (AND ":" SPACING))
 (ESRAP:DEFRULE EQUAL
     (AND "=" SPACING))
 (ESRAP:DEFRULE NOT_EQUAL
     (AND "<>" SPACING))
 (ESRAP:DEFRULE LT
     (AND "<" SPACING))
 (ESRAP:DEFRULE LE
     (AND "<=" SPACING))
 (ESRAP:DEFRULE GE
     (AND ">=" SPACING))
 (ESRAP:DEFRULE GT
     (AND ">" SPACING))
 (ESRAP:DEFRULE LPAREN
     (AND "(" SPACING))
 (ESRAP:DEFRULE RPAREN
     (AND ")" SPACING))
 (ESRAP:DEFRULE LBRACK
     (AND "[" SPACING))
 (ESRAP:DEFRULE LBRACK2
     (AND "(." SPACING))
 (ESRAP:DEFRULE RBRACK
     (AND "]" SPACING))
 (ESRAP:DEFRULE RBRACK2
     (AND ".)" SPACING))
 (ESRAP:DEFRULE POINTER
     (AND "^" SPACING))
 (ESRAP:DEFRULE AT
     (AND "@" SPACING))
 (ESRAP:DEFRULE DOT
     (AND "." SPACING))
 (ESRAP:DEFRULE DOTDOT
     (AND ".." SPACING))
 (ESRAP:DEFRULE LCURLY
     (AND "{" SPACING))
 (ESRAP:DEFRULE RCURLY
     (AND "}" SPACING))
 (ESRAP:DEFRULE UNIT
     (AND "unit" SPACING))
 (ESRAP:DEFRULE INTERFACE
     (AND "interface" SPACING))
 (ESRAP:DEFRULE USES
     (AND "uses" SPACING))
 (ESRAP:DEFRULE STRING
     (AND "string" SPACING))
 (ESRAP:DEFRULE IMPLEMENTATION
     (AND "implementation" SPACING))
 (ESRAP:DEFRULE TRUE
     (AND "true" SPACING))
 (ESRAP:DEFRULE FALSE
     (AND "false" SPACING))
 (ESRAP:DEFRULE WS
     PSPACE)
 (ESRAP:DEFRULE COMMENT
     (OR COMMENT_1 COMMENT_2))
 (ESRAP:DEFRULE COMMENT_1
     (AND "(*" (* CHARACTER) "*)"))
 (ESRAP:DEFRULE COMMENT_2
     (AND "{" (+ NOTBRACE) "}"))
 (ESRAP:DEFRULE NOTBRACE
     (AND (ESRAP:! "}") CHARACTER))
 (ESRAP:DEFRULE STRING_LITERAL
     (AND (ESRAP:CHARACTER-RANGES #\') (* (ESRAP:CHARACTER-RANGES (#\! #\')))
          (ESRAP:CHARACTER-RANGES #\')))
 (ESRAP:DEFRULE NUM_INT
     (+ (ESRAP:CHARACTER-RANGES (#\0 #\9))))
 (ESRAP:DEFRULE NUM_REAL
     (OR (AND (+ (ESRAP:CHARACTER-RANGES (#\0 #\9))) EXPONENT)
         (AND (+ (ESRAP:CHARACTER-RANGES (#\0 #\9))) "."
              (+ (ESRAP:CHARACTER-RANGES (#\0 #\9))) (ESRAP:? EXPONENT))
         EXPONENT))
 (ESRAP:DEFRULE EXPONENT
     (AND "e" (ESRAP:? (OR "+" "-")) (+ (ESRAP:CHARACTER-RANGES (#\0 #\9)))))
 (ESRAP:DEFRULE FILE_CUT
     (AND "-h-" SPACING (* DIR) FILENAME FILEEXT SPACING NUM_INT ENDOFLINE))
 (ESRAP:DEFRULE DIR
     (AND IDENT "/"))
 (ESRAP:DEFRULE FILENAME
     IDENT)
 (ESRAP:DEFRULE KEYWORD
     (OR "and" "array" "begin" "boolean" "case" "char" "chr" "const" "div" "do"
         "downto" "else" "end" "file" "for" "function" "goto" "if" "in"
         "integer" "label" "mod" "nil" "not" "of" "or" "packed" "procedure"
         "program" "real" "record" "repeat" "set" "then" "to" "type" "until"
         "var" "while" "with" "unit" "interface" "uses" "string"
         "implementation" "true" "false"))
 (ESRAP:DEFRULE IDENT
     (AND (ESRAP:! KEYWORD) (ESRAP:CHARACTER-RANGES (#\A #\Z) (#\a #\z))
          (* (ESRAP:CHARACTER-RANGES (#\A #\Z) #\- (#\a #\z) (#\0 #\9) #\_))))
 (ESRAP:DEFRULE FILEEXT
     (AND "." IDENT))
 (ESRAP:DEFRULE SPACING
     (* (OR PSPACE COMMENT))
   (:LAMBDA (LIST) (DECLARE (IGNORE LIST)) (VALUES)))
 (ESRAP:DEFRULE PSPACE
     (OR " " "	" ENDOFLINE)
   (:LAMBDA (LIST) (DECLARE (IGNORE LIST)) (VALUES)))
 (ESRAP:DEFRULE ENDOFLINE
     (OR "
"
         "
"
         "")
   (:LAMBDA (LIST) (DECLARE (IGNORE LIST)) (VALUES)))
 (ESRAP:DEFRULE ENDOFFILE
     (ESRAP:! CHARACTER)
   (:LAMBDA (LIST) (DECLARE (IGNORE LIST)) (VALUES))))
